---
- hosts: Dev
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - include: one.yml
    - name: restart httpd
      service: name=httpd state=restarted

    - name: install git
      action: yum name=git state=present
